---
- name: andrewrothstein.unarchive-deps
  version: v1.2.4
- name: andrewrothstein.temurin
  version: 1.1.4
- name: andrewrothstein.service_account
  version: v0.2.0
- name: andrewrothstein.systemd_service
  version: v3.1.0
