---
- role: andrewrothstein.unarchive-deps
  version: v1.2.3
- role: andrewrothstein.temurin
  version: 0.1.3
- role: andrewrothstein.service_account
  version: v0.0.1
- role: andrewrothstein.systemd_service
  version: v3.0.3
